### PR TITLE
Modified .travis.yml to use new scripts

### PR DESCRIPTION
**Pull request by christophernhill**

### CODE REVIEW

**Comment by christophernhill** [comment]
Hmmmm - travis step seems quite a bit slower now. I think this is because the -devel option changes compile options e.g. 

```
  if test "x$DEVEL" = x ; then  #- no optimisation + IEEE :
    FOPTIM='-O0'
  else                          #- development/check options:
    FOPTIM='-O0 -g -fbounds-check'
    FOPTIM="$FOPTIM -ffpe-trap=invalid,zero,overflow -finit-real=inf"
  fi

```

Now take > 20 mins to run Travis tests.

**Comment by edoddridge** [comment]
27 minutes doesn't seem like a deal breaker to me.

I'm a little confused - this looks like it requires the scripts from #19 to work.

**Comment by christophernhill** [comment]
@edoddridge the 27 minute note was just so we had a reminder of why it changed.

There are two PRs because I was trying some experiment to see if there was a way to do PRs for .travis that allowed some testing, but didn't spam the PR with every little debug test (since push to github is only way to test things in travis). The experiment didn't work as I had hoped, so it ended up with 2 PRs!

**Comment by edoddridge** [comment]
OK. You can enable Travis for your fork and set it to run the feature branch - that way whenever you push to the feature branch it will get tested. That section of the manual is currently empty, but I should fix that at some stage.

**Comment by christophernhill** [comment]
Good to add some doc. The actual challenge though is following

1. Once PR is made from source fork or branch in same repo github
automatically syncs PR to every push to source

2. With Travis this means every little subsequent incremental tweak that
you want to test gets “grabbed” by the PR machinery.

3. The result is small things like some formatting and reformatting of YAML
to look nice fill PR with spam.

4. Not a big deal, but different to things where testing for typos etc..,
can be done locally as you go and only pushed at more selected points with
a squash on all the intermediate spam.

**Comment by edoddridge** [comment]
Sure, once you've opened a PR we all get notified every time there's a push, but I don't understand why you need to open the PR before you think it's ready.

**Pull request merged**
